INSERT INTO schema_14 (first_name, middle_name, last_name, email) values
('Иван', 'Иванович', 'Иванов', 'ivanov@my.example.com'),
('Петр', 'Петрович', 'Петров','petrov@my.example.com'),
('Иван', 'Петрович', 'Сидоров', 'sidorov@my.example.com'),
('Ягьяева', 'Сабрина', 'Серверовна', 'sabrina@my.example.com'),
( 'Сергей', 'Александрович', 'Сергеев', 'sergeev@my.example.com'),
('Дмитрий', 'Олегович', 'Смирнов', 'smirnov@my.example.com'),
('Алексей', 'Викторович', 'Кузнецов', 'kuznetsov@my.example.com'),
('Николай', 'Андреевич', 'Попов','popov@my. example.com' ),
('Михаил', 'Денисович', 'Соколов','sokolov@my.example.com'),
('Андрей', 'Максимович', 'Волков', 'volkov@my.example.com'),
('Мария', 'Алексеевна', 'Орлова', 'orlova@my.example.com'),
('Тимофей', 'Романович', 'Беляев', 'belyaev@my.example.com'),
('Ольга', 'Владимировна', 'Морозова', 'morozova@my.example.com'),
('Егор', 'Станиславович', 'Фёдоров', 'fedorov@my.example.com'),
('Никита', 'Павлович', 'Громов', 'gromov@my.example.com'),
('Алина', 'Дмитриевна', 'Лебедева', 'lebedeva@my.example.com'),
('Владислав', 'Игоревич', 'Тарасов', 'tarasov@my.example.com'),
('Екатерина', 'Сергеевна', 'Зайцева', 'zaitseva@my.example.com'),
('Роман', 'Андреевич', 'Киселёв', 'kiselev@my.example.com'),
('Дарья', 'Алексеевна', 'Панина', 'panina@my.example.com'),
('Максим', 'Витальевич', 'Богданов', 'bogdanov@my.example.com'),
('Артём', 'Константинович', 'Жуков', 'zhukov@my.example.com'),
('Светлана', 'Олеговна', 'Фролова', 'frolova@my.example.com'),
('Илья', 'Николаевич', 'Ершов', 'ershov@my.example.com');
